# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  @sdk_map = {
    sdk_env: "prod", # "dev", "prod"
    sdk_configuration: "Release", # "Debug", "Release"
    sdk_dryrun: false,
    # sdk_module_current: nil,
    # sdk_release_version: nil,
    # sdk_xcodeproj_path: nil,
    # sdk_output_dir: nil,
  }
  p @sdk_map

  @sdk_module_names = ["Core", "Banner", "OMAdapter", "A2A"]

  def set_env param
    if param.count > 0
      @sdk_map.merge!(param)
      p "merged SDK MAP: #{@sdk_map}"
    end

    if !@sdk_map[:sdk_module_current]
      p "Not found parameter :sdk_module_current. Pick one from #{@sdk_module_names}"
      exit!
    end

    if !@sdk_map[:sdk_xcodeproj_path] 
      @sdk_map[:sdk_xcodeproj_path] = "#{@sdk_map[:sdk_module_current]}/#{@sdk_map[:sdk_module_current]}.xcodeproj"
    end

    if @sdk_map[:sdk_release_version]
      increment_version_number(
        bump_type: "patch",
        version_number: @sdk_map[:sdk_release_version],
        xcodeproj: @sdk_map[:sdk_xcodeproj_path],
      )
    else
      @sdk_map[:sdk_release_version] = increment_version_number(
        bump_type: "patch",
        xcodeproj: @sdk_map[:sdk_xcodeproj_path],
      )
    end

    @sdk_map[:sdk_output_dir] = "build/#{@sdk_map[:sdk_configuration]}"

    p "sdk map: #{@sdk_map}"
  end

  lane :package do |param|
    p param
    set_env param
    p "xcodebuild #{@sdk_map[:sdk_xcodeproj_path]} for #{@sdk_map[:sdk_configuration]} into #{@sdk_map[:sdk_output_dir]}"
    xcodebuild(
      raw_buildlog: true,
      project: @sdk_map[:sdk_xcodeproj_path],
      target: "Aggregate",
      configuration: @sdk_map[:sdk_configuration],
      build_settings: { :SDK_OUTPUT_DIR => @sdk_map[:sdk_output_dir] },
    )
  end

  lane :deploy_to_gcs_dev do |param|
    set_env param
    google_cloud_storage_upload(
      project: "rd2n-dev",
      keyfile: ENV["GOOGLE_APPLICATION_CREDENTIALS"],
      bucket: "rssp-dev-cdn",
      content_path: "#{@sdk_map[:sdk_module_current]}/#{@sdk_map[:sdk_output_dir]}/#{param[:file_name]}",
      name: "sdk/ios/#{@sdk_map[:sdk_release_version]}/#{param[:file_name]}",
    )
    project = "rd2n-dev"
    bucket = "rssp-dev-cdn"
    source_file = "../#{@sdk_map[:sdk_module_current]}/#{@sdk_map[:sdk_output_dir]}/#{param[:file_name]}"
    target_file = "gs://#{bucket}/sdk/ios/#{@sdk_map[:sdk_env]}/#{@sdk_map[:sdk_release_version]}/#{param[:file_name]}"
    
    puts("cp #{source_file} #{target_file}")
    if !@sdk_map[:sdk_dryrun]
      # system("gsutil cp #{source_file} #{target_file}")
    end
  end

  lane :deploy_to_gcs do |param|
      p "TODO"
  end

  lane :update_podspec do |param|
    set_env param

    env = @sdk_map[:sdk_env] == "prod" ? "" : ".#{@sdk_map[:sdk_env]}"
    path = "Release/cocoapods/RUNA#{@sdk_map[:sdk_module_current]}#{env}.podspec"

    version_bump_podspec(
      path: path,
      version_number: @sdk_map[:sdk_release_version],
    )

    puts("public push to Rakuten-Ads-iOS")
    if !@sdk_map[:sdk_dryrun]
      pod_push(
        path: path,
        repo: 'Rakuten-Ads-iOS',
        skip_tests: true,
        verbose: true,
      )
    end
  end

  lane :github_release_tag do |param|
    set_env param
    version = @sdk_map[:sdk_release_version]

    assets = []
    if @sdk_map[:sdk_configuration] == "Release"
      assets = @sdk_module_names.map { |module_name| "#{module_name}/#{@sdk_map[:sdk_output_dir]}/RUNA#{module_name}_iOS_#{version}.framework.zip" }
    end

    p "push release tag #{version} with assets [#{assets}]"
    if !@sdk_map[:sdk_dryrun]
      set_github_release(
        repository_name: "rakuten-ads/Rakuten-Ads-iOS",
        api_token: ENV["FASTLANE_GITHUB_TOKEN"],
        name: version,
        tag_name: version,
        description: "release for #{version}",
        upload_assets: assets,
      )
    end
  end

  lane :release do |param|
    if param[:module]
      @sdk_module_names = [param[:module]]
    end

    @sdk_module_names.each do |module_name|
      @sdk_map = {
        sdk_env: "prod",
        sdk_configuration: "Release",
        # sdk_module_current: nil,
        # sdk_release_version: nil,
        # sdk_xcodeproj_path: nil,
        # sdk_output_dir: nil,
        sdk_dryrun: false
      }

      @sdk_map[:sdk_module_current] = module_name
      set_env param
      package
      deploy_to_gcs_dev file_name: "RUNA#{module_name}_iOS_#{@sdk_map[:sdk_release_version]}.framework.zip"
      update_podspec
    end

    github_release_tag

  end
end

