default_platform(:ios)

platform :ios do
  lane :scan do
    run_tests(
  	project: "Banner/Banner.xcodeproj",
  	scheme: "Banner",
  	clean: false,
	skip_build: true,
	open_report: true,
	code_coverage: true,
	force_quit_simulator: true
	)
    run_tests(
  	project: "Core/Core.xcodeproj",
  	scheme: "Core",
  	clean: false,
	skip_build: true,
	open_report: true,
	code_coverage: true,
	force_quit_simulator: true
	)
  end
end

